---
after_script:
- util/ci after_script
before_script:
- util/ci before_script
language: ruby
branches:
  only:
    - master
    - auto
    - /[\d.]+/
    - /.+-stable$/
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.7
- 2.2.3
- 2.3.1
- ruby-head
env:
  - "YAML=syck TEST_TOOL=rubygems"
  - "YAML=psych TEST_TOOL=rubygems"
  - "TEST_TOOL=bundler RGV=master"
script:
- util/ci script
matrix:
  exclude:
    - rvm: 1.8.7
      env: "YAML=psych"
    - rvm: 2.0.0
      env: "YAML=syck"
    - rvm: 2.1.7
      env: "YAML=syck"
    - rvm: 2.2.3
      env: "YAML=syck"
    - rvm: 2.3.1
      env: "YAML=syck"
    - rvm: ruby-head
      env: "YAML=syck"
  allow_failures:
    - rvm: ruby-head
